### ISSUE TITLE
Step 5 console error

### ISSUE THREAD

**Issue by SpicySnow** [A3M4/Personal-YouTube-PDF-Report-Generator#13]
I get this error when I try to do step 5. I tried to upgrade pip using 'python -m pip installs --upgrade pip' but still doesn't works.
![image](https://user-images.githubusercontent.com/58118944/70862497-77b46a80-1f3d-11ea-94a5-829783400909.png)

**Comment by A3M4** [comment]
This issue has been fixed by deleting pylab in requirement.txt, you can download the new version of requirement.txt

**Comment by SpicySnow** [comment]
> This issue has been fixed by deleting pylab in requirement.txt, you can download the new version of requirement.txt

thanks, issue fixed but I have new which I will have to fix by myself. Google is making all the takeout data in my language (polish) and yeah... I will have to edit the script so this will work for me as well but I think this will be a good lesson to learn some python. thank you again.
